### ISSUE TITLE
QGIS Mindestanforderungen prüfen

### ISSUE THREAD

**Issue by DirkThalheim** [ChrFr/qgis-geocoder#10]
Das PlugIn ließ sich bei uns nur in neueren QGIS Versionen (ab 3.10.x) installieren und nutzen. In älteren Versionen (z.B.  3.2.1 Bonn) kam nach der Installation eine Fehlermeldung. Die Mindestanforderungen an QGIS sind zu überprüfen und in der PlugIn-Beschreibung zu korrigieren. Es sollte mindestens die aktuelle LTR-Version (3.10.8) unterstützt werden.

Fehlermeldung aus dem 3.2.1 Test:

```
Konnte Erweiterung 'bkggeocoder' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 
ImportError: cannot import name 'QgsRasterMarkerSymbolLayer' 
Traceback (most recent call last):
  File "C:/Program Files/QGIS 3.2/apps/qgis/./python\qgis\utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/hain/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bkggeocoder\__init__.py", line 39, in classFactory
    from .bkg_geocoder_main import BKGGeocoderPlugin
  File "C:/Program Files/QGIS 3.2/apps/qgis/./python\qgis\utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/hain/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bkggeocoder\bkg_geocoder_main.py", line 35, in 
    from .interface.main_widget import MainWidget
  File "C:/Program Files/QGIS 3.2/apps/qgis/./python\qgis\utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/hain/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bkggeocoder\interface\main_widget.py", line 41, in 
    from interface.dialogs import ReverseResultsDialog, InspectResultsDialog
  File "C:/Program Files/QGIS 3.2/apps/qgis/./python\qgis\utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\hain\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\bkggeocoder\interface\dialogs.py", line 32, in 
    from qgis.core import (QgsPointXY, QgsGeometry, QgsVectorLayer, QgsFeature,
ImportError: cannot import name 'QgsRasterMarkerSymbolLayer'

Python-Version: 
3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS-Version: 3.2.1-Bonn Bonn, 1edf372fb8 
Python-Pfad:
•	C:/Users/hain/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThToolBox
•	C:/Users/hain/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\extlibs
•	C:/Program Files/QGIS 3.2/apps/qgis/./python
•	C:/Users/hain/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/hain/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
•	C:/Program Files/QGIS 3.2/apps/qgis/./python/plugins
•	C:\Program Files\QGIS 3.2\bin\python36.zip
•	C:\Program Files\QGIS 3.2\apps\Python36\DLLs
•	C:\Program Files\QGIS 3.2\apps\Python36\lib
•	C:\Program Files\QGIS 3.2\bin
•	C:\Program Files\QGIS 3.2\apps\Python36
•	C:\Program Files\QGIS 3.2\apps\Python36\lib\site-packages
•	C:\Program Files\QGIS 3.2\apps\Python36\lib\site-packages\win32
•	C:\Program Files\QGIS 3.2\apps\Python36\lib\site-packages\win32\lib
•	C:\Program Files\QGIS 3.2\apps\Python36\lib\site-packages\Pythonwin
•	C:/Users/hain/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	D:/TEMP_QGIS/webshop
•	C:\Users\hain\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\bkggeocoder
•	C:\Users\hain\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\bkggeocoder
•	C:\Users\hain\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\bkggeocoder
•	C:\Users\hain\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\bkggeocoder
```

**Comment by ChrFr** [comment]
die Mindestversion ist QGIS 3.6
